net_node/Models/Album.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace net_node.Models
{
    public class Album
    {
        [BsonId]
        public ObjectId Id { get; set; }
        public string AlbumName { get; set; }

        public string Artist { get; set; }
        public DateTime ReleaseDate { get; set; }
        public int Duration { get; set; }
        public List<Song> Songs { get; set; }
    }
}

net_node/Models/ErrorViewModel.cs
namespace net_node.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

net_node/Models/Song.cs
namespace net_node.Models
{
    public class Song
    {
        public string Name { get; set; }
        public int Duration { get; set; }
    }
}

net_node/Models/SongViewModel.cs
namespace net_node.Models
{
    public class SongViewModel
    {
        public Song Song { get; set; }
        public string AlbumId { get; set; }

    }
}

net_node/Controllers/AlbumController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using net_node.Models;
using net_node.Repositories;

namespace net_node.Controllers
{
    public class AlbumController : Controller
    {
        private IAlbumCollection db = new AlbumCollection();
        // GET: AlbumController
        public ActionResult Index()
        {
            var albums = db.GetAllAlbum();
            return View(albums);
        }

        // GET: AlbumController/Details/5
        public ActionResult Details(string id)
        {
            var album = db.GetAlbumId(id);
            return View(album);
        }

        // GET: AlbumController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AlbumController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                var album = new Album()
                {
                    AlbumName = collection["AlbumName"],
                    Duration = int.Parse(collection["Duration"]),
                    Artist = collection["Artist"],
                    ReleaseDate = DateTime.Parse(collection["ReleaseDate"])

                };
                db.InsertAlbum(album);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AlbumController/Edit/5
        public ActionResult Edit(string id)
        {
            var album = db.GetAlbumId(id);
            return View(album);
        }

        // POST: AlbumController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, IFormCollection collection)
        {
            try
            {
                var album = new Album()
                {
                    Id= new ObjectId(id),
                    AlbumName = collection["AlbumName"],
                    Duration = int.Parse(collection["Duration"]),
                    Artist = collection["Artist"],
                    ReleaseDate = DateTime.Parse(collection["ReleaseDate"])

                };
                db.UpdateAlbum(album);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AlbumController/Delete/5
        public ActionResult Delete(string id)
        {
            var album = db.GetAlbumId(id);
            return View(album);
        }

        // POST: AlbumController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id, IFormCollection collection)
        {
            try
            {
                db.DeleteAlbum(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

net_node/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using net_node.Models;
using System.Diagnostics;

namespace net_node.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

net_node/Controllers/SongController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using net_node.Models;
using net_node.Repositories;

namespace net_node.Controllers
{
    public class SongController : Controller
    {
        private IAlbumCollection db = new AlbumCollection();
        public IActionResult Index()
        {
            return View();
        }

        // GET: SongController/Create
        public ActionResult Create(string id)
        {
            SongViewModel songVM = new SongViewModel() {AlbumId = id, Song = new Song() };
            return View(songVM);
        }

        // POST: SongController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                var album = db.GetAlbumId(collection["AlbumId"]);
                if (album.Songs == null)
                    album.Songs = new List<Song>();
                album.Songs.Add(new Song
                {
                    Name = collection["Song.Name"],
                    Duration = int.Parse(collection["Song.Duration"])
                });
                db.UpdateAlbum(album);
                return RedirectToAction("index","Album");
            }
            catch
            {
                return View();
            }
        }
    }
}

net_node/Views/Album/Create.cshtml
@model net_node.Models.Album

@{
    ViewData["Title"] = "Create";
}

<h1>Crear album</h1>

<h4>Album</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AlbumName" class="control-label"></label>
                <input asp-for="AlbumName" class="form-control" />
                <span asp-validation-for="AlbumName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Artist" class="control-label"></label>
                <input asp-for="Artist" class="form-control" />
                <span asp-validation-for="Artist" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

net_node/Views/Album/Delete.cshtml
@model net_node.Models.Album

@{
    ViewData["Title"] = "Delete";
}

<h1>ELIMINAR ALBUM</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Album</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlbumName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlbumName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

net_node/Views/Album/Details.cshtml
@model net_node.Models.Album

@{
    ViewData["Title"] = "Details";
}



<div>
    <h4>Album</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlbumName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlbumName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

net_node/Views/Album/Edit.cshtml
@model net_node.Models.Album

@{
    ViewData["Title"] = "Edit";
}
<h1>Editar album</h1>

<h4>Album</h4>
<hr />
<div class="row">
    <div class="col-md-4">
         <div class="form-group">
               @Html.ActionLink("Add Song", "Create","Song",new{id= Model.Id},null)
            </div>
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AlbumName" class="control-label"></label>
                <input asp-for="AlbumName" class="form-control" />
                <span asp-validation-for="AlbumName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Artist" class="control-label"></label>
                <input asp-for="Artist" class="form-control" />
                <span asp-validation-for="Artist" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    @if(Model.Songs !=null){
        <h2>Songs</h2>
        <table class="table">
            <thead>
                <th>Name</th>
                <th>Duration</th>
            </thead>
            <tbody>
                @foreach(var item in Model.Songs)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.Duration)</td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

net_node/Views/Album/index.cshtml
@model IEnumerable<net_node.Models.Album>

@{
    ViewData["Title"] = "index";
}



<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AlbumName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Artist)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReleaseDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AlbumName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Artist)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

net_node/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

net_node/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - net_node</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Zilla+Slab:wght@300&display=swap" />
   <link rel="stylesheet" href="~/css/site.css" />
   
    

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ALBUMS AND SONGS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Album" asp-action="Index">Album</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - net_node - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

net_node/Views/Song/Create.cshtml
@model net_node.Models.SongViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Song</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type = "hiden" asp-for = "AlbumId" />   
            <div class="form-group">
                <label asp-for="Song.Name" class="control-label"></label>
                <input asp-for="Song.Name" class="form-control" />
                <span asp-validation-for="Song.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Song.Duration" class="control-label"></label>
                <input asp-for="Song.Duration" class="form-control" />
                <span asp-validation-for="Song.Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}